module.exports = {
  "rules": {
    "block-no-empty": true,
    "font-family-no-duplicate-names": true,
    "color-no-invalid-hex": true,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "string-no-newline": true,
    "unit-no-unknown" : true,
    "property-no-unknown": true,
    "keyframe-declaration-no-important": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,
    "media-feature-name-no-unknown": true,
    "at-rule-no-unknown": [true, {
      "ignoreAtRules": ["extend"]
    }],
    "comment-no-empty": true,
    "no-descending-specificity": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    "function-url-no-scheme-relative": true,
    "number-max-precision": 4,
    "shorthand-property-no-redundant-values": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-no-important": true,
    "declaration-block-single-line-max-declarations": 1,
    "selector-max-attribute":2,
    "selector-max-class": 3,
    // "selector-class-pattern":  ["^[a-zA-Z-]+[a-zA-Z-]--*[a-zA-Z-]+$", {
    //   "resolveNestedSelectors": true
    // }],
    "selector-max-id": 1,
    "media-feature-name-no-vendor-prefix": true,
    "max-nesting-depth": 3,
    "indentation": 2,
    "at-rule-name-case": "lower",
    "at-rule-empty-line-before": "always",
    "at-rule-name-space-after": "always",
    "no-unknown-animations": true,
    "number-leading-zero": "never",
    "string-quotes": "double",
    "unit-case": "lower",
    "value-keyword-case": "lower",
    "property-case": "lower",
    "declaration-colon-space-after": "always",
    "at-rule-semicolon-newline-after": "always",
    "declaration-empty-line-before": "never",
    "declaration-block-semicolon-newline-after": "always",
    "function-comma-space-before": "never",
    "function-max-empty-lines": 0,
    "function-name-case": "lower",
    "function-parentheses-space-inside": "always",
    "function-comma-space-after": "always",
    "function-url-quotes": "always",
    "length-zero-no-unit": true,
    "value-list-comma-space-after": "always",
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-max-empty-lines": 0,
    "declaration-bang-space-after": "always",
    "declaration-empty-line-before": "never",
    "selector-attribute-brackets-space-inside": "always",
    "selector-attribute-operator-space-after": "always",
    "selector-attribute-operator-space-before": "always",
    "selector-attribute-quotes": "always",
    "selector-combinator-space-before": "always",
    "selector-descendant-combinator-no-non-space": true,
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-colon-notation": "single",
    "selector-type-case": "lower",
    "selector-pseudo-class-parentheses-space-inside": "always",
    "selector-combinator-space-after": "always",
    "block-closing-brace-empty-line-before": "never",
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always",
    "block-opening-brace-newline-after": "always",
    "media-feature-colon-space-before": "always",
    "media-feature-colon-space-after": "always",
    "media-feature-name-case": "lower",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "max-empty-lines": 1,
    "at-rule-semicolon-space-before": "never",
  }
}